<footer>
    &copy <?php echo date('Y'); ?>, LeaguePick. Made by <a href="http://www.joshbour.com">Josh Bour</a>
    <div class="fb-like" data-href="https://www.facebook.com/leaguepick" data-width="110" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
</footer>
<div id="fb-root"></div>
<?php
echo $this->inlineScript()->prependFile(APPLICATION_ENV != "production" ? $this->basePath('js/main.js') : $this->basePath('js/main.min.js'), 'text/javascript')
    ->prependFile(APPLICATION_ENV != "production" ? $this->basePath('js/lib.js') : $this->basePath('js/lib.min.js'), 'text/javascript')
    ->prependFile($this->basePath('js/Gettext.js'), 'text/javascript')
    ->prependFile($this->basePath('js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/jquery.selectbox-0.2.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/perfect-scrollbar.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/html2canvas.js', 'text/javascript'))
    ->prependFile($this->basePath('js/jquery-1.11.0.min.js', 'text/javascript'));