<footer>
    <nav>
        <a href="<?php echo $this->url('about'); ?>">About LeaguePick</a> |
        <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=484HNKDK3MCYA" target="_blank">Buy me a beer</a> |
        <a href="<?php echo $this->url('referral'); ?>">Referral Program</a>
    </nav>
    &copy <?php echo date('Y'); ?>, LeaguePick. Made by <a href="http://www.joshbour.com">Josh Bour</a>.
</footer>
<?php
echo $this->inlineScript()->prependFile($this->basePath('js/main.js'), 'text/javascript')
    ->prependFile($this->basePath('js/lib.js'), 'text/javascript')
    ->prependFile($this->basePath('js/Gettext.js'), 'text/javascript')
    ->prependFile($this->basePath('js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/jquery.selectbox-0.2.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/jquery-1.11.0.min.js', 'text/javascript'));