<?php
echo $this->doctype();
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
$isMobile = $this->mobile();
?>
<html lang="en">
<?php
// The layout's head
echo $this->partial("header", array('child' => $child));
?>
<body<?php echo ($child->bodyClass) ? ' class="' . $child->bodyClass . '"' : ''; ?>>
<noscript>
<div id="nojs">
<?php echo $this->translate("Please enable javascript for the site to work properly."); ?>
</div>
</noscript>
<?php
$messages = $this->flashMessenger()->getMessages();
$clearMessages = array();
if (!empty($messages)) :
    ?>
    <div id="flash">
        <ul class="flashMessages">
            <?php foreach ($messages as $fMessage) : ?>
                <li><?php echo $fMessage; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<?php
$route = $this->routeName();
if ($child->activeRoute)
    $route = $child->activeRoute;

?>
<header>
    <div id="topWrapper">
        <div id="logo">
            <a href="<?php echo $this->url('home'); ?>"
               title="<?php echo $this->translate("LeaguePick"); ?>">LeaguePick Logo</a>
        </div>
        <nav>
            <a href="<?php echo $this->url('home'); ?>"<?php echo $route == "home" ? ' class="active"' : ''; ?> title="Go to homepage">Home</a>
            <a href="<?php echo $this->url('tutorials'); ?>"<?php echo $route == "tutorials" ? ' class="active"' : ''; ?> title="Search for a tutorial">Tutorials</a>
            <a href="<?php echo $this->url('admin/tutorials/add'); ?>"<?php echo $route == "admin/tutorials/add" ? ' class="active"' : ''; ?> title="Add a tutorial">Add Tutorials</a>
            <a href="<?php echo $this->url('about'); ?>"<?php echo $route == "about" ? ' class="active"' : ''; ?> title="Some info about us">About</a>
            <a href="<?php echo $this->url('admin/logout'); ?>"<?php echo $route == "admin/logout" ? ' class="active"' : ''; ?> title="Logout">Logout</a>
        </nav>
    </div>
</header>
<div id="content">
    <?php
    $announcements = array(
        "about" => 'LeaguePick now has an about page, you can check it <a href="' . $this->url('about') . '">here</a> or at the bottom of the page.',
        'referral' => 'We have added our first referral payments as well as some proof and more info on the <a href="' . $this->url('referral') . '">referral page</a>.',
        'facebook' => 'We now have a facebook page! Click <a href="https://www.facebook.com/leaguepick">here</a> and like us :)'
    );
    if (isset($_COOKIE['announcement'])) {
        setcookie("announcement", "", time() - 3600);
    }
    if (isset($_COOKIE['announcements'])) {
        $cookie = json_decode($_COOKIE['announcements'],true);
    } else {
        $cookie = array();
        foreach($announcements as $key => $value){
            $cookie[$key] = true;
        }
        setcookie("announcements", json_encode($cookie), time() + 365 * 24 * 60 * 60, '/');
    }
    $available = array_filter($cookie,function($var){
        return $var;
    });
    if(count($available) > 0):
        $key = array_rand($available);
        $announcement = $announcements[$key];
    ?>
        <div id="announcement" data-target="<?php echo $key; ?>">
            <p>
                <?php echo $announcement; ?>
            </p>
            <div class="remove">X</div>
        </div>
        <?php
    endif;
    ?>
    <?php echo $this->content; ?>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <div id="advertisement">
<!--        <ins class="adsbygoogle"-->
<!--             style="display:inline-block;--><?php //echo $isMobile ? "width:320px;height:50px" : "width:728px;height:90px"; ?><!--"-->
<!--             data-ad-client="ca-pub-6737088231270252"-->
<!--             data-ad-slot="--><?php //echo $isMobile ? "4819041412" : "1963306611"; ?><!--"></ins>-->
<!--        <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>-->
        <!-- START AD CODE -->
        <script language="javascript" type="text/javascript" charset="utf-8">
            var cpxcenter_banner_border = '#336699';
            var cpxcenter_banner_text = '#ffffff';
            var cpxcenter_banner_bg = '#000000';
            cpxcenter_banner_link = '#ffffff';
            cpxcenter_width = <?php echo $isMobile? "300":"728"; ?>;
            cpxcenter_height = <?php echo $isMobile? "50":"90"; ?>;
        </script>
        <script language="JavaScript" type="text/javascript" src="http://ads.cpxcenter.com/cpxcenter/showAd.php?nid=4&amp;zone=<?php echo $isMobile? "73248" : "73250";?>&amp;type=banner&amp;sid=54734&amp;pid=52761&amp;subid=&amp;opt1=&amp;opt2=">
        </script>
    </div>
    <!-- END AD CODE -->
</div>
<?php
// The layout's footer
echo $this->partial("footer", array('child' => $child));
?>
</body>
</html>
