<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Admin\Module'                         => __DIR__ . '/Module.php',
  'Admin\Controller\IndexController'     => __DIR__ . '/src/Admin/Controller/IndexController.php',
  'Admin\Factory\AddTutorialFormFactory' => __DIR__ . '/src/Admin/Factory/AddTutorialFormFactory.php',
  'Admin\Form\AddTutorialFieldset'       => __DIR__ . '/src/Admin/Form/AddTutorialFieldset.php',
  'Admin\Form\AddTutorialForm'           => __DIR__ . '/src/Admin/Form/AddTutorialForm.php',
);
