<?php
echo $this->doctype();
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
$isMobile = $this->mobile();
?>
<html lang="en">
<?php
// The layout's head
echo $this->partial("header", array('child' => $child));
?>
<body<?php echo ($child->bodyClass) ? ' class="' . $child->bodyClass . '"' : ''; ?>>
<noscript>
    <div id="nojs">
        <?php echo $this->translate("Please enable javascript for the site to work properly."); ?>
    </div>
</noscript>
<?php
$messages = $this->flashMessenger()->getMessages();
$clearMessages = array();
if (!empty($messages)) :
    ?>
    <div id="flash">
        <ul class="flashMessages">
            <?php foreach ($messages as $fMessage) : ?>
                <li><?php echo $fMessage; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<?php
$route = $this->routeName();
if ($child->activeRoute)
    $route = $child->activeRoute;

?>
<header>
    <div id="topWrapper">
        <div id="logo">
            <a href="<?php echo $this->url('home'); ?>"
               title="<?php echo $this->translate("LeaguePick"); ?>">LeaguePick Logo</a>
        </div>
        <span>Pick your champion the easy way!</span>
    </div>
</header>
<div id="content">
    <?php echo $this->content; ?>
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<div id="advertisement">
		<ins class="adsbygoogle"
			 style="display:inline-block;<?php echo $isMobile ? "width:320px;height:50px" : "width:728px;height:90px"; ?>"
			 data-ad-client="ca-pub-6737088231270252"
			 data-ad-slot="<?php echo $isMobile ? "4819041412" : "1963306611"; ?>"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
</div>
<?php
// The layout's footer
echo $this->partial("footer", array('child' => $child));
?>
</body>
</html>
