<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'League\Module'                      => __DIR__ . '/Module.php',
  'League\Entity\Champion'             => __DIR__ . '/src/League/Entity/Champion.php',
  'League\Entity\Summoner'             => __DIR__ . '/src/League/Entity/Summoner.php',
  'League\Factory\SummonerFormFactory' => __DIR__ . '/src/League/Factory/SummonerFormFactory.php',
  'League\Form\SummonerFieldset'       => __DIR__ . '/src/League/Form/SummonerFieldset.php',
  'League\Form\SummonerForm'           => __DIR__ . '/src/League/Form/SummonerForm.php',
  'League\Model\GameDto'               => __DIR__ . '/src/League/Model/GameDto.php',
  'League\Model\PlayerDto'             => __DIR__ . '/src/League/Model/PlayerDto.php',
  'League\Model\RawStatsDto'           => __DIR__ . '/src/League/Model/RawStatsDto.php',
  'League\Model\SummonerDto'           => __DIR__ . '/src/League/Model/SummonerDto.php',
  'League\Service\League'              => __DIR__ . '/src/League/Service/League.php',
);
