<div id="main">
    <div id="about" class="increasedLineHeight">
        <ol>
            <li>
                <span class="question">What is LeaguePick?</span>
                <p class="answer">LeaguePick (LP) is a web application that suggests league of legends champions based on the summoner's performance, data and input choices .</p>
            </li>
            <li>
                <span class="question">How do you calculate the LP Score?</span>
                <p class="answer">
                    For obvious reasons we can't really share our algorithm, however it takes into account the summoner's win ratio, games played, kda etc. <br/>
                    It uses data only from the current season and ranked games.
                </p>
            </li>
            <li>
                <span class="question">Why should I use your website?</span>
                <p class="answer">
                    There are many sites around where you can find info about you and your stats. <br />
                    However we want to make these stats extremely personalised, meaning that you can <strong>really</strong> find the best option for you in order to win, <br />
                    by giving more options such as opponent matchup selection and others.
                </p>
            </li>
            <li>
                <span class="question">Why can't I find my profile?</span>
                <p class="answer">The Riot API is kinda weird sometimes and you might have to wait a bit and try again later. Sorry for the inconvenience, not much we can do! </p>
            </li>
            <li>
                <span class="question">Where can I contact you for any business related stuff?</span>
                <p class="answer">You may use the following email for business only: <a href="mailto:business@leaguepick.com">business[at]leaguepick.com</a></p>
            </li>
            <li>
                <span class="question">Why do you say "we" when you are in fact one person?</span>
                <p class="answer">
                    Because I'm a player like everyone. I use this site like all of you do, and trust me I want to get the best results possible. Otherwise what's the point!
                </p>
            </li>
            <li>
                <span class="question">Do you have any relationship to Riot Games?</span>
                <p class="answer">This product is not endorsed, certified or otherwise approved in any way by Riot Games, Inc. or any of its affiliates.</p>
            </li>
        </ol>
    </div>
</div>