<div id="sidebar">
    <div class="contactInfo">
        <?php echo $content->getContent(); ?>
    </div>
</div>
<div id="main">
    <?php
    $form->prepare();
    $form->setAttribute('action', $this->url('contact'));
    $fieldset = $form->get('contact');

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('security'));
    ?>
    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('sender'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('sender'));
        echo $this->formInput($fieldset->get('sender'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('subject'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('subject'));
        echo $this->formInput($fieldset->get('subject'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('body'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('body'));
        echo $this->formTextarea($fieldset->get('body'));
        ?>
    </div>


    <div class="element">
        <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Submit'))); ?>
    </div>

    <?php echo $this->form()->closeTag() ?>
</div>